Feature/administrationmenu
basxsoftwareassociation/basxconnect pull request #182
Opened 2021-11-04 13:13 UTC by dward2nd

- Old setting views related to Administration were moved from basxconnect/core/views/settings_views to basxconnect/core/views/admin_views
- In the Maintenance setting view, a package version list was added.

2021-11-05 04:28 UTC, saemideluxe requested changes
Okay, this looks very good. Just make the changes for translatable strings and fix the warnings for flake8. I updated the flake8 config, there will be two warnings.

You can check it on your own machine with ```pip install flake8 flake8-black``` and then just run ```flake8``` inside the basxconnect repository or you see if pycharm can detect our flake8 configuration (inside the file ```.flake8```).

2021-11-05 04:28 UTC, saemideluxe commented on basxconnect/core/views/admin_views.py
> +        newer_version = "unable to load"
Make this a translatable string please.

2021-11-05 04:28 UTC, saemideluxe commented on basxconnect/core/views/admin_views.py
> +                            cell=(hg.DIV(hg.C("row.package_latest"))),
Make header entries translatable strings.

2021-11-06 06:38 UTC, dward2nd commented
I resolved the visible strings to be translatable as suggested.

2021-11-06 06:52 UTC, saemideluxe commented
Okay, thanks. Did you also see my notes on flake8 linting? If you check details of the basxconnect-ci check, you will see that the flake8 linting fails with two errors:

```bash
./basxconnect/core/views/person/person_modals_views.py:1:1: F401 'bread' imported but unused
./basxconnect/core/layouts/settings_layout.py:2:1: F401 'pkg_resources' imported but unused
```

2021-11-06 08:09 UTC, merged