add: simple test for persons
basxsoftwareassociation/basxconnect pull request #97
Opened 2021-07-06 09:44 UTC by saemideluxe

See https://github.com/basxsoftwareassociation/bread/pull/56

2021-07-07 15:04 UTC, wipascal requested changes
CI is complaining...

2021-07-07 16:35 UTC, saemideluxe commented
Jup, was waiting for the merge on bread.

2021-07-08 06:20 UTC, saemideluxe commented
Okay, I had to fiddle a bit with the github workflow file in order to get the test dependencies correctly. Maybe this needs some more tweaking in the future. Hypothesis also looks at some performance numbers and fails if the generation of instances takes unexpected long. This can be a problem e.g. when the Github limits CPU resources for actions I assume.

2021-07-12 06:09 UTC, wipascal approved these changes

2021-07-12 06:37 UTC, merged